import { useState } from "react";
import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillSkype,
} from "react-icons/ai";
import Image from "next/image";
import deved from "../public/mohsenpic.jpg";
import design from "../public/design.png";
import code from "../public/code.png";
import consulting from "../public/consulting.png";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Mohsen Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10 dark:bg-slate-800 md:px-20 lg:px-40 dark:text-white">
        <section className="min-h-screen">
          <nav className="py-10 mb-2 flex justify-between ">
            <h1 className="text-xl font-burtons dark:text-white">
              developed by Mohsen
            </h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className="cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="mailto:msobhaniasl@gmail.com.com"
                >
                  Request Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-5xl  text-teal-600 font-medium">
              Mohsen Sobhaniasl
            </h2>
            <h3 className="text-2xl pt-5  md:text-3xl ">
              Developer and designer.
            </h3>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-1 text-gray-600">
            <a
              className="hover:text-teal-700"
              href="https://www.linkedin.com/in/mohsen-sobhaniasl-07b366144/"
            >
              {" "}
              <AiFillLinkedin />{" "}
            </a>
            <AiFillTwitterCircle />
            <AiFillSkype />
          </div>
          <div className="dark:bg-slate-400 mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-10 md:h-96 md:w-96">
            <Image src={deved} fill className="object-cover" />
          </div>
        </section>
        <section>
          <div className="p-2">
            <h3 className="text-3xl mt-5 text-center">Services I offer</h3>
            <p className="text-justify text-md leading-8 text-gray-800 mt-10 max-w-2xl mx-auto ms:max-w-lg dark:text-white">
              As a frontend developer with skills in ReactJS, HTML, CSS,
              JavaScript, NextJS, and Tailwind, along with backend expertise in
              NodeJS and MongoDB, I offer a comprehensive range of services.
              These services include developing user-friendly and responsive
              websites, creating custom web applications with scalable backend
              architectures, and building e-commerce
            </p>
            <p className="text-center">
              platforms with secure payment integrations
            </p>
          </div>
          <div className="lg:flex gap-10 ">
            <div className="text-center justify-center shadow-lg p-10 rounded-xl  my-10 dark:bg-white">
              <Image className="m-auto" src={code} height={100} width={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 dark:text-black">
                Frontend Developer
              </h3>
              <p className="py-2 dark:text-black">
                Creating elegant designs suited for you.
              </p>
              <h4 className="py-4 text-teal-600">Design tools I use</h4>
              <p className="text-gray-800 py-1">HTML</p>
              <p className="text-gray-800 py-1">CSS</p>
              <p className="text-gray-800 py-1">Javascript</p>
            </div>
            <div className="text-center justify-center shadow-lg p-10 rounded-xl  my-10 dark:bg-white">
              <Image className="m-auto" src={design} height={100} width={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 dark:text-black">
                Modern Design
              </h3>
              <p className="py-2 dark:text-black">
                Responsive and interactive interfaces
              </p>
              <h4 className="py-4 text-teal-600">Design tools I use</h4>
              <p className="text-gray-800 py-1">React</p>
              <p className="text-gray-800 py-1">Nextjs</p>
              <p className="text-gray-800 py-1">Tailwind</p>
            </div>
            <div className="text-center justify-center shadow-lg p-10 rounded-xl  my-10 dark:bg-white">
              <Image
                className="m-auto"
                src={consulting}
                height={100}
                width={100}
              />
              <h3 className="text-lg font-medium pt-8 pb-2 dark:text-black">
                Backend Developer
              </h3>
              <p className="py-2 dark:text-black">
                Highly scalable and reliable server-side
              </p>
              <h4 className="py-4 text-teal-600">Design tools I use</h4>
              <p className="text-gray-800 py-1">Nodejs</p>
              <p className="text-gray-800 py-1">MongoDB</p>
              <p className="text-gray-800 py-1">Express</p>
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl mt-2 text-center dark:text-white">
              Portofolio
            </h3>
            <p className="text-center text-md leading-8 text-gray-800 max-w-2xl mx-auto ms:max-w-lg dark:text-white">
              As a freelance frontend developer, I am passionate about creating
              beautiful and responsive web interfaces that not only look great
              but also provide a seamless user experience.
            </p>
          </div>
          <div className="flex flex-col gap-10 p-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1 transition ease-in-out delay-150 hover:-translate-y-1 hover:scale-110 duration-300">
              <Image
                src={web1}
                className="rounded-lg object-fill w-full h-96"
              />
            </div>
            <div className="basis-1/3 flex-1 transition ease-in-out delay-150 hover:-translate-y-1 hover:scale-110 duration-300">
              <Image
                src={web2}
                className="rounded-lg object-cover w-full h-96"
              />
            </div>
            <div className="basis-1/3 flex-1 transit-ion ease-in-out delay-150 hover:-translate-y-1 hover:scale-110 duration-300">
              <Image
                src={web3}
                className="rounded-lg object-cover w-full h-96"
              />
            </div>
            <div className="basis-1/3 flex-1 transition ease-in-out delay-150 hover:-translate-y-1 hover:scale-110 duration-300">
              <Image
                src={web4}
                className="rounded-lg object-cover w-full h-96"
              />
            </div>
            <div className="basis-1/3 flex-1 transition ease-in-out delay-150 hover:-translate-y-1 hover:scale-110 duration-300">
              <Image
                src={web5}
                className="rounded-lg object-cover w-full h-96"
              />
            </div>
            <div className="basis-1/3 flex-1 transition ease-in-out delay-150 hover:-translate-y-1 hover:scale-110 duration-300">
              <Image
                src={web6}
                className="rounded-lg object-cover w-full h-96"
              />
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
